frr defaults traditional
hostname ekalinger
log file /var/log/frr/frr_debug.log
service integrated-vtysh-config
!
debug zebra packet detail
debug zebra rib detailed
debug zebra nht detailed
debug zebra dplane detailed
debug zebra dplane dpdk detailed
!
debug vrf
!
vrf r1
 netns /run/netns/r1
exit-vrf
!
vrf r2
 netns /run/netns/r2
exit-vrf
!
router ospf vrf r1
 ospf router-id 172.17.1.1
 maximum-paths 3
 network 10.0.1.1/24 area 0
 network 10.1.1.0/24 area 0
 network 10.2.1.0/24 area 0
 network 10.3.1.0/24 area 0
exit
!
router ospf vrf r2
 ospf router-id 172.17.1.2
 maximum-paths 3
 network 10.1.1.0/24 area 0
 network 10.2.1.0/24 area 0
 network 10.3.1.0/24 area 0
 network 172.172.174.0/24 area 0
exit
!
router ospf
 ospf router-id 172.17.1.3
 network 10.0.1.0/24 area 0
 network 10.10.10.0/24 area 0
 exit
 !